version: '2'
services:
  mysqldb:
    container_name: devops-mysqldb
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    volumes:
      - /home/mysql/data:/var/lib/mysql

  devops-backend:
    image: hamzarahali/devops-backend:8b0b578
    container_name: devops-backend
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
      
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_logs:/opt/SonarQube/logs'

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - 'nexus-data:/nexus-data'
volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data: