services:
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./plugins:/opt/sonarqube/extensions/plugins
    environment:
      SONARQUBE_WEB_JVMARGS: "-Dsonar.prometheus.export.enabled=true"
    depends_on:
      - mysql
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: root
      MYSQL_DATABASE: mysql

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data: